### ISSUE TITLE
Does not run under MacOS Docker Desktop

### ISSUE THREAD

**Issue by kentloving** [bademux/openlighting#1]
Should it? I'm usually confused about making an image work with the vm that is run on the Mac.

On docker run, I get:

Error loading shared library libolaserver.so.0: No such file or directory (needed by /usr/local/bin/olad)
Error loading shared library libolacommon.so.0: No such file or directory (needed by /usr/local/bin/olad)
Error relocating /usr/local/bin/olad: _ZN3ola9OlaDaemonD1Ev: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola6thread12SignalThread20InstallSignalHandlerEiPNS_9Callback0IvEE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola13SetHelpStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola8BaseFlag27ReplaceUnderscoreWithHyphenEPc: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola6thread12SignalThreadC1Ev: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola9OlaDaemon3RunEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola9OlaDaemon4InitEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola20InitLoggingFromFlagsEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola4base7Version10GetVersionB5cxx11Ev: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola9OlaDaemonC1ERKNS_9OlaServer7OptionsEPNS_9ExportMapE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola9DaemoniseEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola20StringToBoolTolerantERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola11GetRegistryEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola12FlagRegistry12RegisterFlagEPNS_13FlagInterfaceE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola7LogLineD1Ev: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola11StringToIntERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPtb: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola6thread12SignalThreadD1Ev: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola8BaseFlag16NewCanonicalNameEPKc: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola9ExportMapD1Ev: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola10ParseFlagsEPiPPc: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola10ServerInitEiPPcPNS_9ExportMapE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola7LogLineC1EPKciNS_9log_levelE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola17IncrementLogLevelEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola2io12SelectServer9TerminateEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola9OlaServer13ReloadPluginsEv: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola4FlagIbE9NO_PREFIXE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola16EXIT_UNAVAILABLEE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola7EXIT_OKE: symbol not found
Error relocating /usr/local/bin/olad: _ZN3ola13logging_levelE: symbol not found

**Comment by bademux** [comment]
Hi, thanks for reporting!
It is a bug, v0.2.1 already baking https://github.com/bademux/openlighting/actions/runs/679563294
Unfortunately it is a looong process ~4hours, but you can build container locally with latest docker-ce:
```bash
docker buildx create --use
# docker run --privileged --rm tonistiigi/binfmt --install all #uncomment if you want to build for arch that is not native for you system
docker buildx build --platform=linux/amd64 --tag bademux/openlighting:latest . --load
```

**Comment by kentloving** [comment]
your v0.2.1 has fixed this issue and this issue can be closed.

Thank you.
