### ISSUE TITLE
Network option of docker run on macOS must be a bit different

### ISSUE THREAD

**Issue by kentloving** [bademux/openlighting#2]
The  docker run option '--net host', does not work like we'd expect when running docker on a mac. Something about the mac's docker vm doesn't get to to see the mac's 'host' network.  So when using --net host, localhost:9090 is not seen from the host. 

But, this works:

docker run -it -v "$(pwd)/configs":/home/olad/.ola/ -p 9090:9090 -p 9010:9010  bademux/openlighting:latest

**Comment by bademux** [comment]
Hello,
It is up to user to choose the best configuration.
Network "host" will not work on windows and Mac due to lack of native docker support. And please don't use it for any kind of production environment unless you know what are you doing.

**Comment by kentloving** [comment]
agreed. This is issue is not a complaint. Just pointing out that the README instructions don't work for a mac.

Thanks again. I appreciate your work.
